// Generated by CoffeeScript 1.6.3
var revolverDemo,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

$(document).ready(revolverDemo = null, revolverDemo = $(".revolver-demo").revolver().data("revolver"), $("input").on("change", function(e) {
  var booleans, error, properties, property, _i, _len, _ref, _ref1;
  properties = {
    returnToStart: false,
    stopOnHover: false
  };
  booleans = $.map(properties, (function(val, key) {
    return key;
  }));
  _ref = $("form").serializeArray();
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    property = _ref[_i];
    if (_ref1 = property.name, __indexOf.call(booleans, _ref1) >= 0) {
      delete properties[property.name];
    } else if (property.value !== "") {
      try {
        properties[property.name] = JSON.parse(property.value);
      } catch (_error) {
        error = _error;
        console.log("Ensure you have a valid value for '" + property.name + "'");
      }
    }
  }
  console.log(properties);
  revolverDemo.reset(properties);
}));
